"use client";
import { ReactNode, useState } from "react";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import apolloClient from "../clients/apolloClient";
import { Nav, Navbar, Sidebar, Toolbar } from "@/components/layout";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <html lang="en">
      <ApolloProvider client={apolloClient}>
        <body className={inter.className}>
          <Navbar />
          <Sidebar isOpen={isOpen} setIsOpen={setIsOpen} />
          <main
            className={
              "max-sm:ml-0 pl-4 transition-all duration-500 ease-in-out " +
              (isOpen ? "ml-64" : "ml-24")
            }
          >
            <Toolbar />
            {children}
          </main>
        </body>
      </ApolloProvider>
    </html>
  );
}
